/***********************************************************
Author 			:	Dawn Greer, DBA
Date Written	:	12/11/2020
Program Title	:	cov_amb_downtime_patinfo
Source File		:	cov_amb_downtime_patinfo.prg
Object Name		:	cov_amb_downtime_patinfo
Directory		:	cust_script
 
Purpose			: 	Ambulatory Downtime Patient Info
Notes: 			:   Copied from cov_amb_downtime_schedule
 
Mod		Date		Engineer				Comment
----    ----------- ----------------------- ---------------------------
 
*************************************************************************/
drop program cov_amb_downtime_patinfo go
create program cov_amb_downtime_patinfo
 
prompt
	"Output to File/Printer/MINE" = "MINE"
	, "Select Facility" = 0
 
with OUTDEV, FAC
 
;FREE RECORD a
RECORD a
(
	1	rec_cnt		=	i4
	1	qual[*]
		2	person_id       =   f8
		2   patient 		=	c100
		2	dob				=	c10
		2   age_as_of_dos   =   i4
		2	home_phone		=	c15
		2	mobile_phone 	=	c15
		2   person_addr     =   c50
		2   person_city     =   c50
		2   person_state    =   c2
		2   person_zip      =   c10
		2	insurance		=	c50
		2	fin				=	c20
		2	appt_date_time	=	c25
		2   appt_date_only  =   c25
		2   appt_date       =   c25
		2   appt_duration   =   i4
		2	appt_status		=   c50
		2 	appt_type		=	c50
		2	appt_reminder	=	c50
		2	visit_reason	=	c100
		2	resource		=	c100
		2	facility		=	c100
		2   rpt_date        =   vc
		2   nkallergies     =   c120
		2   allergies_cnt   =   i4
		2   allergies_qual[*]
			3  allergy_id   =   f8
			3  substance    =   c50
			3  allergy_cat  =   c30
			3  reactions    =   c100
			3  severity     =   c50
			3  allergy_type =   c50
			3  allergy_status = c10
			3  reviewed_dt  =   c25
		2   med_cnt         =   i4
		2   med_qual[*]
			3  location     =   c100
			3  mnemonic     =   c200
			3  long_desc    =   c200
			3  order_details =  c500
			3  order_status =   c25
		2   prob_cnt        =   i4
		2   prob_qual[*]
			3  problem      =   c200
			3  prob_code    =   c50
			3  onset_dt     =   c25
			3  beg_eff_dt   =   c25
			3  end_eff_dt   =   c25
		2   recommend_cnt   =   i4
		2   recommend_qual[*]
			3  recommend_cat =  c100
			3  recommend     =  c100
			3  priority     =   c25
			3  frequency    =   c25
			3  due_date     =   c25
)
 
DECLARE fac_opr_var = c2
DECLARE faclist = c2000
DECLARE facprompt = vc
DECLARE num = i4
DECLARE facitem = vc
DECLARE cnt = i4 WITH PROTECT
DECLARE startdate			= F8
DECLARE enddate				= F8
 
 
SET startdate = CNVTDATETIME(CURDATE,0)
SET enddate = CNVTDATETIME(CURDATE+4,235959)
 
 
/**********************************************************
Get CMG Facility Data
***********************************************************/
 
;Pulling the CMG List for when Any is selected in the Prompt
SELECT facnum = CNVTSTRING(CV.CODE_VALUE)
FROM CODE_VALUE CV, CODE_VALUE_EXTENSION CVE
WHERE CV.CODE_VALUE = CVE.CODE_VALUE
AND CV.CODE_SET = 220
AND CV.CDF_MEANING = 'AMBULATORY'
AND CV.ACTIVE_IND = 1
AND CVE.FIELD_NAME = 'CMG Reporting'
ORDER BY TRIM(CV.DESCRIPTION,3)
 
HEAD REPORT
	faclist = FILLSTRING(2000,' ')
 	faclist = '('
DETAIL
	faclist = BUILD(BUILD(faclist, facnum), ', ')
 
FOOT REPORT
	faclist = BUILD(faclist,')')
	faclist = REPLACE(faclist,',','',2)
 
WITH nocounter
 
;Facility Prompt
IF(SUBSTRING(1,1,REFLECT(PARAMETER(PARAMETER2($FAC),0))) = "L")		;multiple options selected
	SET fac_opr_var = "IN"
	SET facprompt = '('
	SET num = CNVTINT(SUBSTRING(2,2,REFLECT(PARAMETER(PARAMETER2($FAC),0))))
 
	FOR (i = 1 TO num)
		SET facitem = CNVTSTRING(PARAMETER(PARAMETER2($FAC),i))
		SET facprompt = BUILD(facprompt,facitem)
		IF (i != num)
			SET facprompt = BUILD(facprompt, ",")
		ENDIF
	ENDFOR
	SET facprompt = BUILD(facprompt, ")")
	SET facprompt = BUILD("CV_APPT_RES_ALL_LOC_COV.CODE_VALUE IN ",facprompt)
 
ELSEIF(PARAMETER(PARAMETER2($FAC),1)=0.0)  ;any was selected
	SET fac_opr_var = "IN"
	SET facprompt = BUILD("CV_APPT_RES_ALL_LOC_COV.CODE_VALUE IN ", faclist)
ELSE 	;single value selected
	SET fac_opr_var = "="
	SET facitem = CNVTSTRING(PARAMETER(PARAMETER2($FAC),1))
	SET facprompt = BUILD("CV_APPT_RES_ALL_LOC_COV.CODE_VALUE = ", facitem)
ENDIF
 
/**********************************************************
Get Schedule Data
***********************************************************/
CALL ECHO ("Get Schedule Data")
 
SELECT INTO "NL:"
	FIN = TRIM(EA.ALIAS,3)
FROM PERSON PAT
  , (LEFT JOIN PHONE HPHONE ON (PAT.PERSON_ID = HPHONE.PARENT_ENTITY_ID
  		AND HPHONE.PARENT_ENTITY_NAME = 'PERSON'
  		AND HPHONE.ACTIVE_IND = 1
  		AND HPHONE.END_EFFECTIVE_DT_TM > CNVTDATETIME(CURDATE,CURTIME3)
  		AND HPHONE.PHONE_TYPE_CD = 170 /*Home Phone*/
  		AND HPHONE.PHONE_TYPE_SEQ = 1
  		AND HPHONE.PHONE_NUM_KEY != ' '
  	))
  , (LEFT JOIN PHONE MPHONE ON (PAT.PERSON_ID = MPHONE.PARENT_ENTITY_ID
  		AND MPHONE.PARENT_ENTITY_NAME = 'PERSON'
  		AND MPHONE.ACTIVE_IND = 1
  		AND MPHONE.END_EFFECTIVE_DT_TM > CNVTDATETIME(CURDATE,CURTIME3)
  		AND MPHONE.PHONE_TYPE_CD = 4149712.00 /*Mobile Phone*/
  		AND MPHONE.PHONE_TYPE_SEQ = 1
  		AND MPHONE.PHONE_NUM_KEY != ' '
  	))
  , (LEFT JOIN ADDRESS PATADDR ON (PAT.PERSON_ID = PATADDR.PARENT_ENTITY_ID
  		AND PATADDR.PARENT_ENTITY_NAME = 'PERSON'
  		AND PATADDR.ACTIVE_IND = 1
  		AND PATADDR.END_EFFECTIVE_DT_TM > CNVTDATETIME(CURDATE,CURTIME3)
  		AND PATADDR.ADDRESS_TYPE_CD = 756.00 /*Home Addr*/
  		AND PATADDR.ADDRESS_TYPE_SEQ = 1
  		AND PATADDR.STREET_ADDR != ' '
	))
  , (INNER JOIN ENCOUNTER ENC ON (ENC.PERSON_ID=PAT.PERSON_ID
  		AND ENC.ACTIVE_IND = 1
  	))
  , (INNER JOIN ENCNTR_ALIAS EA ON (EA.ENCNTR_ID=ENC.ENCNTR_ID
		AND EA.ACTIVE_IND = 1
		AND EA.END_EFFECTIVE_DT_TM > CNVTDATETIME(CURDATE,CURTIME3)
		AND EA.ENCNTR_ALIAS_TYPE_CD = 1077  /*FIN NBR*/
	))
  , (LEFT JOIN ENCNTR_PLAN_RELTN ENCNTR_PLAN_RELTN2 ON (ENC.ENCNTR_ID=ENCNTR_PLAN_RELTN2.ENCNTR_ID
  		AND ENCNTR_PLAN_RELTN2.PRIORITY_SEQ = 1
  		AND ENCNTR_PLAN_RELTN2.ACTIVE_IND = 1
  	))
  , (LEFT JOIN ORGANIZATION ORGANIZATION_PRIM ON (ORGANIZATION_PRIM.ORGANIZATION_ID=ENCNTR_PLAN_RELTN2.ORGANIZATION_ID
  	))
  , (INNER JOIN SCH_APPT APPT_SCH_APPT ON (APPT_SCH_APPT.ENCNTR_ID=ENC.ENCNTR_ID
  		AND APPT_SCH_APPT.ROLE_MEANING = "PATIENT"
  		AND APPT_SCH_APPT.STATE_MEANING != "RESCHEDULED"
  	))
  , (INNER JOIN SCH_EVENT APPT_SCH_EVENT ON (APPT_SCH_EVENT.SCH_EVENT_ID=APPT_SCH_APPT.SCH_EVENT_ID
    ))
  , (LEFT JOIN SCH_EVENT_DETAIL SCH_EVENT_DETAIL ON (SCH_EVENT_DETAIL.SCH_EVENT_ID = APPT_SCH_EVENT.SCH_EVENT_ID
  		AND SCH_EVENT_DETAIL.OE_FIELD_ID = 23372832 /*Patient Reminder*/
  		AND SCH_EVENT_DETAIL.VERSION_DT_TM > CNVTDATETIME(CURDATE,CURTIME3)
  	))
  , (LEFT JOIN SCH_APPT APPT_SCH_RES_APPT_ALL ON (APPT_SCH_RES_APPT_ALL.SCH_EVENT_ID = APPT_SCH_EVENT.SCH_EVENT_ID
  	))
  , (LEFT JOIN SCH_RESOURCE APPT_SCH_RESOURCE_ALL ON (APPT_SCH_RES_APPT_ALL.RESOURCE_CD=APPT_SCH_RESOURCE_ALL.RESOURCE_CD
    ))
  , (LEFT JOIN CODE_VALUE APPT_RES_RES_CD_ALL ON (APPT_SCH_RESOURCE_ALL.RESOURCE_CD=APPT_RES_RES_CD_ALL.CODE_VALUE
  		AND APPT_RES_RES_CD_ALL.CODE_SET = 14231
  	))
  , (LEFT JOIN CODE_VALUE CV_APPT_RES_ALL_LOC_COV ON (APPT_SCH_RES_APPT_ALL.APPT_LOCATION_CD=CV_APPT_RES_ALL_LOC_COV.CODE_VALUE
  		AND CV_APPT_RES_ALL_LOC_COV.CODE_SET = 220
		AND CV_APPT_RES_ALL_LOC_COV.CDF_MEANING IN ("AMBULATORY")
	))
  , (LEFT JOIN CODE_VALUE_EXTENSION CVE ON (CV_APPT_RES_ALL_LOC_COV.CODE_VALUE = CVE.CODE_VALUE
		AND CVE.FIELD_NAME = 'CMG Reporting'
    ))
WHERE PAT.ACTIVE_IND = 1
AND PARSER(facprompt)
AND APPT_SCH_RESOURCE_ALL.MNEMONIC_KEY IS NOT NULL
AND APPT_SCH_RESOURCE_ALL.MNEMONIC_KEY != ' '
AND APPT_SCH_RES_APPT_ALL.SLOT_STATE_CD IN (0,9541)
AND PAT.NAME_LAST_KEY NOT IN ('FFFFPEDS','FFFFAMB','FFFFPNRC','FFFFOP','FFFFED','FFFFIP','FFFFWH','FFFFTEST','FFFFREVCYCLE',
	'FFFFPHARM','ZZGLOVER','ZZTEST','ZZWICK','ZZBOGUS','ZZZZTESTPW','ZZZREGRESSION','ZZZZBHTEST','ZZZNEUROPW','ZZZFLMCRAD',
	'ZZZFSRRAD', 'ZZZTESTONE','ZZZAMB','ZZZPWRAD','ZZTOPTEST','ZZZ','ZZZRMCRAD','ZZZZTESTPBH','ZZMDDONOTUSE','ZZZMPITESTP',
	'ZZZRADTEST','ZZZFSRGO','ZZZFSWRAD','ZZZTESTIP','ZZZTEST','ZZELLMER','ZZZMPITESTBL','ZZZZTESTPOC','ZZZZZZTEST','ZZZTESTOP',
	'TTTTTEST','TTTTGENLAB','TTTT','TTTTMAYO','TTTTPHARMTEST','TTTTESTFSV','TTTTONC','TTTTESTCATHLAB','TTURNER','TTEST',
	'TTTTHUDLOW','TTTTTESTFN','TTTTCAMCAPTEST','TTTTMDI','TTBACKLOADING','TTTTESTPRVL','TTTTMMC','TTTTQUEST','TTHOMASON',
	'TTTTPRINTER','TTTTEST')
AND APPT_SCH_RES_APPT_ALL.BEG_DT_TM BETWEEN CNVTDATETIME(startdate) AND CNVTDATETIME(enddate)
ORDER BY TRIM(CV_APPT_RES_ALL_LOC_COV.DESCRIPTION,3), TRIM(APPT_RES_RES_CD_ALL.DESCRIPTION,3), APPT_SCH_RES_APPT_ALL.BEG_DT_TM
 
HEAD REPORT
	cnt = 0
	CALL alterlist(a->qual, 10)
 
DETAIL
	cnt = cnt + 1
	IF (mod(cnt,10) = 1 OR cnt = 1)
		stat = alterlist(a->qual, cnt + 9)
	ENDIF
 
	a->qual[cnt].person_id      =   PAT.PERSON_ID
	a->qual[cnt].patient 		= 	TRIM(PAT.NAME_FULL_FORMATTED,3)
	a->qual[cnt].dob			= 	FORMAT(CNVTDATETIMEUTC(PAT.BIRTH_DT_TM,1),"MM/DD/YYYY;;d")
	a->qual[cnt].age_as_of_dos  =   FLOOR((DATETIMEDIFF(APPT_SCH_RES_APPT_ALL.BEG_DT_TM, PAT.BIRTH_DT_TM)/365))
	a->qual[cnt].home_phone	 	=	EVALUATE2(IF (SIZE(TRIM(HPHONE.PHONE_NUM,3)) = 10)
  		CONCAT("(",SUBSTRING(1,3,HPHONE.PHONE_NUM),") ",SUBSTRING(4,3,HPHONE.PHONE_NUM),"-",SUBSTRING(7,4,HPHONE.PHONE_NUM))
  		ELSE " " ENDIF)
	a->qual[cnt].mobile_phone	=	EVALUATE2(IF (SIZE(TRIM(MPHONE.PHONE_NUM,3)) = 10)
  		CONCAT("(",SUBSTRING(1,3,MPHONE.PHONE_NUM),") ",SUBSTRING(4,3,MPHONE.PHONE_NUM),"-",SUBSTRING(7,4,MPHONE.PHONE_NUM))
  		ELSE " " ENDIF)
	a->qual[cnt].person_addr    =   TRIM(PATADDR.STREET_ADDR,3)
	a->qual[cnt].person_city    =   TRIM(PATADDR.CITY,3)
	a->qual[cnt].person_state   =   TRIM(PATADDR.STATE,3)
	a->qual[cnt].person_zip     =   TRIM(SUBSTRING(1,5, PATADDR.ZIPCODE),3)
	a->qual[cnt].insurance		=	TRIM(ORGANIZATION_PRIM.ORG_NAME,3)
	a->qual[cnt].fin			= 	TRIM(EA.ALIAS,3)
	a->qual[cnt].appt_date_time	=	CNVTUPPER(FORMAT(APPT_SCH_RES_APPT_ALL.BEG_DT_TM, "hh:mm;;S"))
	a->qual[cnt].appt_date_only	=	FORMAT(APPT_SCH_RES_APPT_ALL.BEG_DT_TM, "MM/DD/YYYY")
	a->qual[cnt].appt_date	    =	FORMAT(APPT_SCH_RES_APPT_ALL.BEG_DT_TM, "MM/DD/YYYY hh:mm:ss")
	a->qual[cnt].appt_duration  =   CNVTINT(DATETIMEDIFF(APPT_SCH_RES_APPT_ALL.END_DT_TM,APPT_SCH_RES_APPT_ALL.BEG_DT_TM,4))
	a->qual[cnt].appt_status	=	UAR_GET_CODE_DISPLAY(APPT_SCH_EVENT.SCH_STATE_CD)
	a->qual[cnt].appt_type		=	UAR_GET_CODE_DISPLAY(APPT_SCH_EVENT.APPT_TYPE_CD)
	a->qual[cnt].appt_reminder	=	TRIM(SCH_EVENT_DETAIL.OE_FIELD_DISPLAY_VALUE,3)
	a->qual[cnt].visit_reason	=	TRIM(APPT_SCH_EVENT.APPT_REASON_FREE,3)
	a->qual[cnt].resource		=	TRIM(APPT_RES_RES_CD_ALL.DESCRIPTION,3)
	a->qual[cnt].facility		=	TRIM(CV_APPT_RES_ALL_LOC_COV.DESCRIPTION,3)
 	a->qual[cnt].rpt_date       =   FORMAT(CNVTDATETIME(CURDATE,CURTIME3), "MM/DD/YYYY hh:mm:ss;;q")
 
FOOT REPORT
	stat = alterlist(a->qual, cnt )
	a->rec_cnt = cnt
WITH nocounter, separator= CHAR(9), FORMAT
 
 
/**********************************************************
Get No Known Allergies Data
***********************************************************/
CALL ECHO ("Get No Known Allergies Data")
 
IF (a->rec_cnt > 0)
	SELECT DISTINCT INTO "NL:"
		PAT_PERSON_ID = ALLERGY_PERSON.PERSON_ID
		, NKALLERGIES = LISTAGG(TRIM(NOM_ALLERGY.SOURCE_STRING,3),", ")
			OVER(PARTITION BY ALLERGY_PERSON.PERSON_ID ORDER BY ALLERGY_PERSON.PERSON_ID)
	FROM (dummyt d WITH seq = VALUE(SIZE(a->qual,5)))
		, ALLERGY ALLERGY_PERSON
		, NOMENCLATURE NOM_ALLERGY
		, PERSON PAT
		, ENCOUNTER ENC
		, SCH_APPT APPT_SCH_APPT
		, SCH_EVENT APPT_SCH_EVENT
		, SCH_APPT APPT_SCH_RES_APPT_ALL
		, SCH_RESOURCE APPT_SCH_RESOURCE_ALL
		, CODE_VALUE APPT_RES_RES_CD_ALL
		, CODE_VALUE CV_APPT_RES_ALL_LOC_COV
		, CODE_VALUE_EXTENSION CVE
	PLAN d
	JOIN ALLERGY_PERSON WHERE ALLERGY_PERSON.PERSON_ID = a->qual[d.seq].person_id
		AND ALLERGY_PERSON.ACTIVE_IND = 1
		AND ALLERGY_PERSON.ACTIVE_STATUS_CD = 188 /*Active*/
		AND ALLERGY_PERSON.END_EFFECTIVE_DT_TM > CNVTDATETIME(CURDATE,CURTIME3)
		AND ALLERGY_PERSON.REACTION_STATUS_CD NOT IN (3300.00 /*Cancelled*/)
	JOIN NOM_ALLERGY WHERE NOM_ALLERGY.NOMENCLATURE_ID = ALLERGY_PERSON.SUBSTANCE_NOM_ID
		AND NOM_ALLERGY.ACTIVE_IND = 1
		AND NOM_ALLERGY.END_EFFECTIVE_DT_TM > CNVTDATETIME(CURDATE,CURTIME3)
		AND NOM_ALLERGY.NOMENCLATURE_ID IN (960419.00 /*No Known Allergies*/,
	    57826136.00 /*No Known Environmental Allergies*/,57826131.00 /*No Known Food Allergies*/,
	     22283278.00 /*No Known Medication Allergies*/)
	JOIN PAT WHERE ALLERGY_PERSON.PERSON_ID = PAT.PERSON_ID
		AND PAT.ACTIVE_IND = 1
		AND PAT.NAME_LAST_KEY NOT IN ('FFFFPEDS','FFFFAMB','FFFFPNRC','FFFFOP','FFFFED','FFFFIP','FFFFWH','FFFFTEST','FFFFREVCYCLE',
			'FFFFPHARM','ZZGLOVER','ZZTEST','ZZWICK','ZZBOGUS','ZZZZTESTPW','ZZZREGRESSION','ZZZZBHTEST','ZZZNEUROPW','ZZZFLMCRAD',
			'ZZZFSRRAD', 'ZZZTESTONE','ZZZAMB','ZZZPWRAD','ZZTOPTEST','ZZZ','ZZZRMCRAD','ZZZZTESTPBH','ZZMDDONOTUSE','ZZZMPITESTP',
			'ZZZRADTEST','ZZZFSRGO','ZZZFSWRAD','ZZZTESTIP','ZZZTEST','ZZELLMER','ZZZMPITESTBL','ZZZZTESTPOC','ZZZZZZTEST','ZZZTESTOP',
			'TTTTTEST','TTTTGENLAB','TTTT','TTTTMAYO','TTTTPHARMTEST','TTTTESTFSV','TTTTONC','TTTTESTCATHLAB','TTURNER','TTEST',
			'TTTTHUDLOW','TTTTTESTFN','TTTTCAMCAPTEST','TTTTMDI','TTBACKLOADING','TTTTESTPRVL','TTTTMMC','TTTTQUEST','TTHOMASON',
			'TTTTPRINTER','TTTTEST')
	JOIN ENC WHERE ENC.PERSON_ID=PAT.PERSON_ID
		AND ENC.ENCNTR_ID = ALLERGY_PERSON.ENCNTR_ID
  		AND ENC.ACTIVE_IND = 1
	JOIN APPT_SCH_APPT WHERE APPT_SCH_APPT.PERSON_ID=ENC.PERSON_ID
  		AND APPT_SCH_APPT.ROLE_MEANING = "PATIENT"
  		AND APPT_SCH_APPT.STATE_MEANING != "RESCHEDULED"
 	JOIN APPT_SCH_EVENT WHERE APPT_SCH_EVENT.SCH_EVENT_ID=APPT_SCH_APPT.SCH_EVENT_ID
    JOIN APPT_SCH_RES_APPT_ALL WHERE APPT_SCH_RES_APPT_ALL.SCH_EVENT_ID = APPT_SCH_EVENT.SCH_EVENT_ID
    	AND APPT_SCH_RES_APPT_ALL.BEG_DT_TM BETWEEN CNVTDATETIME(startdate) AND CNVTDATETIME(enddate)
  	JOIN APPT_SCH_RESOURCE_ALL WHERE APPT_SCH_RES_APPT_ALL.RESOURCE_CD=APPT_SCH_RESOURCE_ALL.RESOURCE_CD
  		AND APPT_SCH_RESOURCE_ALL.MNEMONIC_KEY IS NOT NULL
		AND APPT_SCH_RESOURCE_ALL.MNEMONIC_KEY != ' '
		AND APPT_SCH_RES_APPT_ALL.SLOT_STATE_CD IN (0,9541)
    JOIN APPT_RES_RES_CD_ALL WHERE APPT_SCH_RESOURCE_ALL.RESOURCE_CD=APPT_RES_RES_CD_ALL.CODE_VALUE
  		AND APPT_RES_RES_CD_ALL.CODE_SET = 14231
	JOIN CV_APPT_RES_ALL_LOC_COV WHERE APPT_SCH_RES_APPT_ALL.APPT_LOCATION_CD=CV_APPT_RES_ALL_LOC_COV.CODE_VALUE
  		AND CV_APPT_RES_ALL_LOC_COV.CODE_SET = 220
		AND CV_APPT_RES_ALL_LOC_COV.CDF_MEANING IN ("AMBULATORY")
		AND PARSER(facprompt)
	JOIN CVE WHERE CV_APPT_RES_ALL_LOC_COV.CODE_VALUE = CVE.CODE_VALUE
		AND CVE.FIELD_NAME = 'CMG Reporting'
 
	FOOT ALLERGY_PERSON.PERSON_ID
		a->qual[d.seq].nkallergies	= NKALLERGIES
 
	WITH nocounter, separator= CHAR(9), FORMAT
ENDIF
 
/**********************************************************
Get Allergies Data
***********************************************************/
CALL ECHO ("Get Allergies Data")
 
IF (a->rec_cnt > 0)
 
	SELECT DISTINCT INTO "NL:"
		ALLERGY_PERSON_ID = ALLERGY_PERSON.PERSON_ID
		,SUBSTANCE = EVALUATE2(IF (SIZE(TRIM(NOM_ALLERGY.SOURCE_STRING,3)) != 0)
			TRIM(CNVTUPPER(NOM_ALLERGY.SOURCE_STRING),3) ELSE TRIM(CNVTUPPER(ALLERGY_PERSON.SUBSTANCE_FTDESC),3) ENDIF)
		,ALLERGY_CAT = UAR_GET_CODE_DISPLAY(ALLERGY_PERSON.SUBSTANCE_TYPE_CD)
		,REACTIONS =  EVALUATE2(IF (SIZE(TRIM(NOM_REACTION.SOURCE_STRING,3)) != 0)
			TRIM(NOM_REACTION.SOURCE_STRING,3) ELSE TRIM(REACTION_PERSON.REACTION_FTDESC,3) ENDIF)
		,SEVERITY = UAR_GET_CODE_DISPLAY(ALLERGY_PERSON.SEVERITY_CD)
		,ALLERGY_TYPE = UAR_GET_CODE_DISPLAY(ALLERGY_PERSON.REACTION_CLASS_CD)
		,ALLERGY_STATUS = UAR_GET_CODE_DISPLAY(ALLERGY_PERSON.REACTION_STATUS_CD)
		,REVIEWED_DT = CONCAT(FORMAT(ALLERGY_PERSON.REVIEWED_DT_TM, "MM/DD/YYYY"), " ",
				CNVTUPPER(FORMAT(ALLERGY_PERSON.REVIEWED_DT_TM, "hh:mm;;S")))
	FROM (dummyt d WITH seq = VALUE(SIZE(a->qual,5)))
		, ALLERGY ALLERGY_PERSON
		, NOMENCLATURE NOM_ALLERGY
		, REACTION REACTION_PERSON
		, NOMENCLATURE NOM_REACTION
		, PERSON PAT
		, ENCOUNTER ENC
		, SCH_APPT APPT_SCH_APPT
		, SCH_EVENT APPT_SCH_EVENT
		, SCH_APPT APPT_SCH_RES_APPT_ALL
		, SCH_RESOURCE APPT_SCH_RESOURCE_ALL
		, CODE_VALUE APPT_RES_RES_CD_ALL
		, CODE_VALUE CV_APPT_RES_ALL_LOC_COV
		, CODE_VALUE_EXTENSION CVE
	PLAN d
	JOIN ALLERGY_PERSON WHERE ALLERGY_PERSON.PERSON_ID = a->qual[d.seq].person_id
		AND ALLERGY_PERSON.ACTIVE_IND = 1
		AND ALLERGY_PERSON.ACTIVE_STATUS_CD = 188 /*Active*/
		AND ALLERGY_PERSON.END_EFFECTIVE_DT_TM > CNVTDATETIME(CURDATE,CURTIME3)
		AND ALLERGY_PERSON.REACTION_STATUS_CD NOT IN (3300.00 /*Cancelled*/)
	JOIN NOM_ALLERGY WHERE NOM_ALLERGY.NOMENCLATURE_ID = ALLERGY_PERSON.SUBSTANCE_NOM_ID
		AND NOM_ALLERGY.ACTIVE_IND = 1
		AND NOM_ALLERGY.END_EFFECTIVE_DT_TM > CNVTDATETIME(CURDATE,CURTIME3)
		AND NOM_ALLERGY.NOMENCLATURE_ID NOT IN (960419.00 /*No Known Allergies*/,
	    57826136.00 /*No Known Environmental Allergies*/,57826131.00 /*No Known Food Allergies*/,
	     22283278.00 /*No Known Medication Allergies*/)
	JOIN REACTION_PERSON WHERE REACTION_PERSON.ALLERGY_INSTANCE_ID = OUTERJOIN(ALLERGY_PERSON.ALLERGY_INSTANCE_ID)
		AND REACTION_PERSON.ACTIVE_IND = OUTERJOIN(1)
		AND REACTION_PERSON.ACTIVE_STATUS_CD = OUTERJOIN(188 /*Active*/)
		AND REACTION_PERSON.END_EFFECTIVE_DT_TM > OUTERJOIN(CNVTDATETIME(CURDATE,CURTIME3))
	JOIN NOM_REACTION WHERE OUTERJOIN(REACTION_PERSON.REACTION_NOM_ID) = NOM_REACTION.NOMENCLATURE_ID
	JOIN PAT WHERE ALLERGY_PERSON.PERSON_ID = PAT.PERSON_ID
		AND PAT.ACTIVE_IND = 1
		AND PAT.NAME_LAST_KEY NOT IN ('FFFFPEDS','FFFFAMB','FFFFPNRC','FFFFOP','FFFFED','FFFFIP','FFFFWH','FFFFTEST','FFFFREVCYCLE',
			'FFFFPHARM','ZZGLOVER','ZZTEST','ZZWICK','ZZBOGUS','ZZZZTESTPW','ZZZREGRESSION','ZZZZBHTEST','ZZZNEUROPW','ZZZFLMCRAD',
			'ZZZFSRRAD', 'ZZZTESTONE','ZZZAMB','ZZZPWRAD','ZZTOPTEST','ZZZ','ZZZRMCRAD','ZZZZTESTPBH','ZZMDDONOTUSE','ZZZMPITESTP',
			'ZZZRADTEST','ZZZFSRGO','ZZZFSWRAD','ZZZTESTIP','ZZZTEST','ZZELLMER','ZZZMPITESTBL','ZZZZTESTPOC','ZZZZZZTEST','ZZZTESTOP',
			'TTTTTEST','TTTTGENLAB','TTTT','TTTTMAYO','TTTTPHARMTEST','TTTTESTFSV','TTTTONC','TTTTESTCATHLAB','TTURNER','TTEST',
			'TTTTHUDLOW','TTTTTESTFN','TTTTCAMCAPTEST','TTTTMDI','TTBACKLOADING','TTTTESTPRVL','TTTTMMC','TTTTQUEST','TTHOMASON',
			'TTTTPRINTER','TTTTEST')
	JOIN ENC WHERE ENC.PERSON_ID=PAT.PERSON_ID
		AND ENC.ENCNTR_ID = ALLERGY_PERSON.ENCNTR_ID
  		AND ENC.ACTIVE_IND = 1
	JOIN APPT_SCH_APPT WHERE APPT_SCH_APPT.PERSON_ID=ENC.PERSON_ID
  		AND APPT_SCH_APPT.ROLE_MEANING = "PATIENT"
  		AND APPT_SCH_APPT.STATE_MEANING != "RESCHEDULED"
 	JOIN APPT_SCH_EVENT WHERE APPT_SCH_EVENT.SCH_EVENT_ID=APPT_SCH_APPT.SCH_EVENT_ID
    JOIN APPT_SCH_RES_APPT_ALL WHERE APPT_SCH_RES_APPT_ALL.SCH_EVENT_ID = APPT_SCH_EVENT.SCH_EVENT_ID
    	AND APPT_SCH_RES_APPT_ALL.BEG_DT_TM BETWEEN CNVTDATETIME(startdate) AND CNVTDATETIME(enddate)
  	JOIN APPT_SCH_RESOURCE_ALL WHERE APPT_SCH_RES_APPT_ALL.RESOURCE_CD=APPT_SCH_RESOURCE_ALL.RESOURCE_CD
  		AND APPT_SCH_RESOURCE_ALL.MNEMONIC_KEY IS NOT NULL
		AND APPT_SCH_RESOURCE_ALL.MNEMONIC_KEY != ' '
		AND APPT_SCH_RES_APPT_ALL.SLOT_STATE_CD IN (0,9541)
    JOIN APPT_RES_RES_CD_ALL WHERE APPT_SCH_RESOURCE_ALL.RESOURCE_CD=APPT_RES_RES_CD_ALL.CODE_VALUE
  		AND APPT_RES_RES_CD_ALL.CODE_SET = 14231
	JOIN CV_APPT_RES_ALL_LOC_COV WHERE APPT_SCH_RES_APPT_ALL.APPT_LOCATION_CD=CV_APPT_RES_ALL_LOC_COV.CODE_VALUE
  		AND CV_APPT_RES_ALL_LOC_COV.CODE_SET = 220
		AND CV_APPT_RES_ALL_LOC_COV.CDF_MEANING IN ("AMBULATORY")
		AND PARSER(facprompt)
	JOIN CVE WHERE CV_APPT_RES_ALL_LOC_COV.CODE_VALUE = CVE.CODE_VALUE
		AND CVE.FIELD_NAME = 'CMG Reporting'
	ORDER BY ALLERGY_PERSON_ID, SUBSTANCE, ALLERGY_CAT, REACTIONS,SEVERITY, ALLERGY_TYPE,
	ALLERGY_STATUS,REVIEWED_DT
 
	HEAD ALLERGY_PERSON.PERSON_ID
		cnt = 0
		idx = 0
		subcnt = 0
		idx = LOCATEVAL(cnt,1,SIZE(a->qual,5),ALLERGY_PERSON.PERSON_ID, a->qual[cnt].person_id)
 
	HEAD ALLERGY_PERSON.ALLERGY_ID
		subcnt = subcnt + 1
 
		IF (mod(subcnt,10)>0)
			CALL ALTERLIST(a->qual[idx].allergies_qual, subcnt + (10-mod(subcnt,10)))
		ENDIF
 
	FOOT ALLERGY_PERSON.ALLERGY_ID
 
		IF (mod(subcnt,10) = 1)
			CALL ALTERLIST(a->qual[idx].allergies_qual, subcnt + 9)
		ENDIF
 
	 	a->qual[idx].allergies_qual[subcnt].allergy_id = ALLERGY_PERSON.ALLERGY_ID
		a->qual[idx].allergies_qual[subcnt].substance =	EVALUATE2(IF (SIZE(TRIM(NOM_ALLERGY.SOURCE_STRING,3)) != 0)
			TRIM(NOM_ALLERGY.SOURCE_STRING,3) ELSE TRIM(ALLERGY_PERSON.SUBSTANCE_FTDESC,3) ENDIF)
		a->qual[idx].allergies_qual[subcnt].allergy_cat = UAR_GET_CODE_DISPLAY(ALLERGY_PERSON.SUBSTANCE_TYPE_CD)
		a->qual[idx].allergies_qual[subcnt].reactions =  EVALUATE2(IF (SIZE(TRIM(NOM_REACTION.SOURCE_STRING,3)) != 0)
			TRIM(NOM_REACTION.SOURCE_STRING,3) ELSE TRIM(REACTION_PERSON.REACTION_FTDESC,3) ENDIF)
		a->qual[idx].allergies_qual[subcnt].severity = UAR_GET_CODE_DISPLAY(ALLERGY_PERSON.SEVERITY_CD)
		a->qual[idx].allergies_qual[subcnt].allergy_type = UAR_GET_CODE_DISPLAY(ALLERGY_PERSON.REACTION_CLASS_CD)
		a->qual[idx].allergies_qual[subcnt].allergy_status = UAR_GET_CODE_DISPLAY(ALLERGY_PERSON.REACTION_STATUS_CD)
		a->qual[idx].allergies_qual[subcnt].reviewed_dt = CONCAT(FORMAT(ALLERGY_PERSON.REVIEWED_DT_TM, "MM/DD/YYYY"), " ",
				CNVTUPPER(FORMAT(ALLERGY_PERSON.REVIEWED_DT_TM, "hh:mm;;S")))
 
	FOOT ALLERGY_PERSON.PERSON_ID
 
		a->qual[idx].allergies_cnt = subcnt
		CALL ALTERLIST(a->qual[idx].allergies_qual, subcnt)
 
		idx = LOCATEVAL(cnt,(idx+1), SIZE(a->qual,5),ALLERGY_PERSON_ID, a->qual[cnt].person_id)
		subcnt = 0
 
	WITH nocounter, separator= CHAR(9), FORMAT
ENDIF
 
CALL ECHORECORD(a)
 
GO TO exitscript
#exitscript
 
END
GO
 
 