 
 
/*****************************************************************************
  Covenant Health Information Technology
  Knoxville, Tennessee
******************************************************************************
 
	Author:			Geetha Paramasivam
	Date Written:		Feb'22
	Solution:			All
	Source file name:	      cov_dsch_medrec_alert_tracking.prg
	Object name:		Nursing/Case management
	Request#:			10022
 	Program purpose:	      Part of Discharge Med rec rule
 	Executing from:		Rule
  	Special Notes:
 
******************************************************************************
  GENERATED MODIFICATION CONTROL LOG
******************************************************************************
 
Mod Date	Developer			Comment
----------	--------------------	------------------------------------------
 
******************************************************************************/
 
 
drop program cov_dsch_medrec_alert_tracking:dba go
create program cov_dsch_medrec_alert_tracking:dba
 
prompt
	"Output to File/Printer/MINe" = "MINE"       ;* Enter or select the printer or file name to send this report to.
	, "Start Discharged Date/Time" = "SYSDATE"
	, "End Discharged Date/Time" = "SYSDATE"
	, "Select Facility" = 0
 
with OUTDEV, start_datetime, end_datetime, facility_list
 
 
/**************************************************************
; VARIABLE DECLARATION
**************************************************************/
 
declare disch_instruction_var  = f8 with constant(uar_get_code_by("DISPLAY", 72, "Discharge Instructions")),protect
declare disch_summary_var      = f8 with constant(uar_get_code_by("DISPLAY", 72, "Discharge Summary")),protect
declare disch_medrec_alrt_var  = f8 with constant(uar_get_code_by("DISPLAY", 72, "Discharge Medrec Alteration Alert")),protect
 
declare encntrid_var = f8 with noconstant(0.0), protect
declare personid_var = f8 with noconstant(0.0), protect
declare userid_var    = f8 with noconstant(0.0), protect
declare log_message = vc with noconstant('')
declare log_misc1   = vc with noconstant('')
declare alert_id_var  = f8 with noconstant(0.0)
 
;set userid_var   = reqinfo->updt_id ;12428721.00
 
 
/**************************************************************
; CCL SCRIPT STARTS HERE
**************************************************************/
 
Record pat(
	1 rec_cnt = i4
	1 plist[*]
		2 facility = vc
		2 fin = vc
		2 pat_name = vc
		2 encntrid = f8
		2 patientid = f8
		2 dschdoc[*]
			3 user_id_print_dsch_inst = f8
			3 user_name_print_dsch_inst = vc
			3 dsch_inst_print_dq_dt = f8
			3 dsch_inst_print_str_dt = vc
			3 user_id_print_dsch_sum = f8
			3 user_name_print_dsch_sum = vc
			3 dsch_sum_print_dq_dt = f8
			3 dsch_sum_print_str_dt = vc
		2 alert[*]
			3 alertid = f8
			3 alrt_type = vc
			3 alrt_dt = dq8
			3 users_alrt_received = vc
			3 users_alrt_dt = vc ;user + alert date/time
			3 users_acpt_alrt = vc
			;3 dsch_inst_print_dt = vc ;after alert
			;3 user_print_dsch_inst = vc
	)
 
 
;==========================================================================================
;Alerts generated by the rule
 
select into $outdev
 
e.encntr_id, eh.send_dt_tm, eh.alert_id, eh.*
 
from eks_alert_esc_hist eh
	,encounter e
 
plan e where e.loc_facility_cd = $facility_list
	and e.active_ind = 1
 
join eh where eh.encntr_id = e.encntr_id
	and eh.send_dt_tm between cnvtdatetime($start_datetime) and cnvtdatetime($end_datetime)
	and eh.msg_type_cd = value(uar_get_code_by("DISPLAY", 30420, "Notify"))
	and eh.subject_text IN('*Discharge Medication Alert - Case Management', '*Discharge Medication Alert - Nursing')
	and eh.alert_source IN('COV_DSCH_MEDREC_TSK', 'COV_DSCH_MEDREC_TSK_REMIN')
 
order by eh.encntr_id, eh.alert_id
 
Head report
	cnt = 0
Head eh.encntr_id
	cnt += 1
	if (mod(cnt,10) = 1 or cnt = 1)
		stat = alterlist(pat->plist, cnt + 9)
	endif
	pat->rec_cnt = cnt
	pat->plist[cnt].facility = uar_get_code_display(e.loc_facility_cd)
	pat->plist[cnt].encntrid = eh.encntr_id
	pat->plist[cnt].patientid = e.person_id
	acnt = 0
Head eh.alert_id
	acnt += 1
	if (mod(acnt,10) = 1 or acnt = 1)
		stat = alterlist(pat->plist[cnt].alert, acnt + 9)
	endif
	pat->plist[cnt].alert[acnt].alertid = eh.alert_id
	pat->plist[cnt].alert[acnt].alrt_type = eh.subject_text
	pat->plist[cnt].alert[acnt].alrt_dt = eh.send_dt_tm
Foot eh.encntr_id
	stat = alterlist(pat->plist[cnt].alert, acnt)
Foot report
	stat = alterlist(pat->plist, cnt)
 
with nocounter
 
if(pat->rec_cnt > 0)
 
;==========================================================================================
;Discharge Inst & Summary
 
select into $outdev
ce.encntr_id, ce.event_end_dt_tm, ce.event_cd, ce.performed_prsnl_id, ce.*
 
from (dummyt d1 with seq = pat->rec_cnt)
	,clinical_event ce
	, prsnl pr
 
plan d1
 
join ce where ce.encntr_id = pat->plist[d1.seq].encntrid
	and ce.event_cd in(disch_instruction_var, disch_summary_var)
	and ce.valid_until_dt_tm = cnvtdatetime ("31-DEC-2100 00:00:00" )
	and ce.result_status_cd IN (23.00, 34.00, 25.00, 35.00)
	and ce.view_level = 1
 
join pr where pr.person_id = ce.performed_prsnl_id
 
order by ce.encntr_id, ce.event_id
 
Head ce.encntr_id
	icnt = 0
	idx = 0
      idx = locateval(icnt ,1 ,pat->rec_cnt ,ce.encntr_id ,pat->plist[icnt].encntrid)
      dcnt = 0
Head ce.event_id
	if(idx > 0)
		dcnt += 1
		if (mod(dcnt,10) = 1 or dcnt = 1)
			stat = alterlist(pat->plist[idx].dschdoc, dcnt + 9)
		endif
 
		case(ce.event_cd)
			of disch_instruction_var:
				pat->plist[idx].dschdoc[dcnt].dsch_inst_print_dq_dt = ce.event_end_dt_tm
				pat->plist[idx].dschdoc[dcnt].dsch_inst_print_str_dt = format(ce.event_end_dt_tm, 'mm-dd/yy hh:mm:ss;;q')
				pat->plist[idx].dschdoc[dcnt].user_id_print_dsch_inst = ce.performed_prsnl_id
				pat->plist[idx].dschdoc[dcnt].user_name_print_dsch_inst = pr.name_full_formatted
			of disch_summary_var:
				pat->plist[idx].dschdoc[dcnt].dsch_sum_print_dq_dt = ce.event_end_dt_tm
				pat->plist[idx].dschdoc[dcnt].dsch_sum_print_str_dt = format(ce.event_end_dt_tm, 'mm-dd/yy hh:mm:ss;;q')
				pat->plist[idx].dschdoc[dcnt].user_id_print_dsch_sum = ce.performed_prsnl_id
				pat->plist[idx].dschdoc[dcnt].user_name_print_dsch_sum = pr.name_full_formatted
		endcase
	endif
Foot ce.encntr_id
	stat = alterlist(pat->plist[idx].dschdoc, dcnt)
with nocounter
 
;==========================================================================================
;Users received the alert
 
select into $outdev
  eh.*
 
from (dummyt d1 with seq = pat->rec_cnt)
	,(dummyt   d2  with seq = 1)
	,eks_alert_esc_hist eh
	,prsnl pr
 
plan d1 where maxrec(d2, size(pat->plist[d1.seq].alert, 5))
join d2
 
join eh where eh.encntr_id = pat->plist[d1.seq].encntrid
	and eh.alert_id = pat->plist[d1.seq].alert[d2.seq].alertid
			and eh.parent_entity_id != null
			and eh.parent_entity_name = 'PERSON'
 
join pr where pr.person_id = eh.parent_entity_id
 
order by eh.encntr_id, eh.alert_id, eh.parent_entity_id
 
Head eh.encntr_id
	icnt = 0
	idx = 0
      idx = locateval(icnt ,1 ,pat->rec_cnt ,eh.encntr_id ,pat->plist[icnt].encntrid)
Head eh.alert_id
	users_alerted = fillstring(2000," ")
	icnt1 = 0
	idx1 = 0
      idx1 = locateval(icnt1 ,1 ,pat->rec_cnt ,eh.alert_id ,pat->plist[idx].alert[icnt1].alertid )
Head eh.parent_entity_id
	users_alerted = build2(trim(users_alerted),'[' ,trim(pr.name_full_formatted),']',',')
Foot eh.alert_id
	pat->plist[idx].alert[idx1].users_alrt_received = replace(trim(users_alerted),",","",2)
with nocounter
 
;==========================================================================================
;Users Accept Alert

select into $outdev
alrtid = pat->plist[d1.seq].alert[d2.seq].alertid, ce.encntr_id, ce.event_cd, ce.result_val
 
from (dummyt d1 with seq = pat->rec_cnt)
	,(dummyt   d2  with seq = 1)
	,clinical_event ce
	 
plan d1 where maxrec(d2, size(pat->plist[d1.seq].alert, 5))
join d2
 
join ce where ce.encntr_id = pat->plist[d1.seq].encntrid
	and ce.event_cd = disch_medrec_alrt_var
 
;Event -  Discharge Medrec Alteration Alert
;Result - Case Management Alert - 3907999

with nocounter, separator=" ", format, uar_code(d,1), format(date,"mm-dd-yyyy hh:mm:ss;;d"), time = 120

 
;==========================================================================================
 
call echorecord(pat)
;==========================================================================================
 
 
select tt = substring(25, 7, 'Case Management Alert - 3907999')  from dummyt 
 
 
 
 
endif ;rec_cnt
 
#exitscript
 
end go
 
 
;with nocounter, separator=" ", format, uar_code(d,1), format(date,"mm-dd-yyyy hh:mm:ss;;d"), time = 120
;go to exitscript
 
 
